{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "In \\[2\\]:\n",
    "\n",
    "    sample_tuple=(1,56,3.5,\"hi\",1+2j)\n",
    "    sample_tuple\n",
    "\n",
    "Out\\[2\\]:\n",
    "\n",
    "    (1, 56, 3.5, 'hi', (1+2j))\n",
    "\n",
    "In \\[4\\]:\n",
    "\n",
    "    sample_tuple=1,56,3.5,\"hi\",1+2j\n",
    "    sample_tuple\n",
    "\n",
    "Out\\[4\\]:\n",
    "\n",
    "    (1, 56, 3.5, 'hi', (1+2j))\n",
    "\n",
    "In \\[5\\]:\n",
    "\n",
    "    type(sample_tuple)\n",
    "\n",
    "Out\\[5\\]:\n",
    "\n",
    "    tuple\n",
    "\n",
    "In \\[6\\]:\n",
    "\n",
    "    sample_tuple[2]\n",
    "\n",
    "Out\\[6\\]:\n",
    "\n",
    "    3.5\n",
    "\n",
    "In \\[7\\]:\n",
    "\n",
    "    sample_tuple[7]\n",
    "\n",
    "    ---------------------------------------------------------------------------\n",
    "    IndexError                                Traceback (most recent call last)\n",
    "    <ipython-input-7-b7a95ea2e8a0> in <module>\n",
    "    ----> 1 sample_tuple[7]\n",
    "\n",
    "    IndexError: tuple index out of range\n",
    "\n",
    "In \\[8\\]:\n",
    "\n",
    "    sample_tuple.reverse()\n",
    "\n",
    "    ---------------------------------------------------------------------------\n",
    "    AttributeError                            Traceback (most recent call last)\n",
    "    <ipython-input-8-ad9148e49edb> in <module>\n",
    "    ----> 1 sample_tuple.reverse()\n",
    "\n",
    "    AttributeError: 'tuple' object has no attribute 'reverse'\n",
    "\n",
    "In \\[9\\]:\n",
    "\n",
    "    sample_tuple(3)\n",
    "\n",
    "    ---------------------------------------------------------------------------\n",
    "    TypeError                                 Traceback (most recent call last)\n",
    "    <ipython-input-9-b7ba7e1274ed> in <module>\n",
    "    ----> 1 sample_tuple(3)\n",
    "\n",
    "    TypeError: 'tuple' object is not callable\n",
    "\n",
    "In \\[10\\]:\n",
    "\n",
    "    sample_tuple(13)\n",
    "\n",
    "    ---------------------------------------------------------------------------\n",
    "    TypeError                                 Traceback (most recent call last)\n",
    "    <ipython-input-10-f7701c2b2f4a> in <module>\n",
    "    ----> 1 sample_tuple(13)\n",
    "\n",
    "    TypeError: 'tuple' object is not callable\n",
    "\n",
    "In \\[11\\]:\n",
    "\n",
    "    sample_tuple.append(5)\n",
    "\n",
    "    ---------------------------------------------------------------------------\n",
    "    AttributeError                            Traceback (most recent call last)\n",
    "    <ipython-input-11-3b12d66566fd> in <module>\n",
    "    ----> 1 sample_tuple.append(5)\n",
    "\n",
    "    AttributeError: 'tuple' object has no attribute 'append'\n",
    "\n",
    "In \\[12\\]:\n",
    "\n",
    "    sample_tuple.remove(\"hi\")\n",
    "\n",
    "    ---------------------------------------------------------------------------\n",
    "    AttributeError                            Traceback (most recent call last)\n",
    "    <ipython-input-12-3662405e17c6> in <module>\n",
    "    ----> 1 sample_tuple.remove(\"hi\")\n",
    "\n",
    "    AttributeError: 'tuple' object has no attribute 'remove'\n",
    "\n",
    "In \\[13\\]:\n",
    "\n",
    "    x=(1,2,3)\n",
    "    y=list(x)\n",
    "    y\n",
    "\n",
    "Out\\[13\\]:\n",
    "\n",
    "    [1, 2, 3]\n",
    "\n",
    "In \\[14\\]:\n",
    "\n",
    "    y.remove(3)\n",
    "    y\n",
    "\n",
    "Out\\[14\\]:\n",
    "\n",
    "    [1, 2]\n",
    "\n",
    "In \\[17\\]:\n",
    "\n",
    "    tuple=(10,20,30)\n",
    "    name_list=list(tuple)\n",
    "    name_list\n",
    "\n",
    "Out\\[17\\]:\n",
    "\n",
    "    [10, 20, 30]\n",
    "\n",
    "In \\[18\\]:\n",
    "\n",
    "    y.append(34)\n",
    "\n",
    "In \\[ \\]:"
   ]
  }
 ],
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {}
}
